version: '3.6'
services: 

#------------------------------
# Banco base Web API service
#------------------------------
  banco-base-web-api:
    image: 'banco-base-web-api:1.0.0'
    deploy:
      resources:
          limits:
            cpus: '1'
            memory: 1024M
    restart: always
    environment:
      - SERVER_IP=host.docker.internal
      - SERVER_IP_KAFKA=host.docker.internal
      - SERVER_IP_DB=host.docker.internal
    depends_on: 
      - mysql
      - kafka
    ports:
      - 8080:8080
    networks:
       code-challlenge-banco-base-net:
        aliases: 
          - banco-base-web-api

#------------------------------
#MySQL data base
#------------------------------
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - LANG=C.UTF-8
    volumes:
      - ./sql/initial_script.sql:/docker-entrypoint-initdb.d/initial_script.sql
    healthcheck:
      test: mysql --user=user --password=password -e "SHOW DATABASES UP;"
      interval: 1s
      timeout: 3s
      retries: 3
    networks: 
      code-challlenge-banco-base-net:
        aliases: 
          - mysql

#------------------------------
# Zookeeper and kafka container
#------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks: 
      code-challlenge-banco-base-net:
        aliases: 
          - zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092,PLAINTEXT_INTERNAL://broker:29092 #actualizar a localhost en local
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks: 
      code-challlenge-banco-base-net:
        aliases: 
          - kafka

#------------------------------
# General resources
#------------------------------
volumes:
  mysql_data:

networks:
  code-challlenge-banco-base-net:
    ipam:
      config:
        - subnet: 172.18.0.0/16
